name: Test-WebHook
on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, beta, rc, stable)"
        required: true
        default: "rc"
      series:
        description: "release sprint series name"
        required: false
        default: ""

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: save release info
        run: |
          rm -f changed.txt
          rm -f versions.json
          echo "@microsoft/teamsfx-server@2.0.7-beta.2024032106.0" > changed.txt
          echo '[  {    "name": "@microsoft/teamsfx-api",    "version": "0.22.8-beta.2024032106.0",    "private": false,    "location": "/home/runner/work/TeamsFx/TeamsFx/packages/api"  },  {    "name": "@microsoft/eslint-plugin-teamsfx",    "version": "0.0.4",    "private": true,    "location": "/home/runner/work/TeamsFx/TeamsFx/packages/eslint-plugin-teamsfx"  },  {    "name": "@microsoft/teamsfx-core",    "version": "2.0.8-beta.2024032106.0",    "private": false,    "location": "/home/runner/work/TeamsFx/TeamsFx/packages/fx-core"  },  {    "name": "@microsoft/teams-manifest",    "version": "0.1.4-beta.2024032106.0",    "private": false,    "location": "/home/runner/work/TeamsFx/TeamsFx/packages/manifest"  },  {    "name": "@microsoft/teamsfx-server",    "version": "2.0.7-beta.2024032106.0",    "private": true,    "location": "/home/runner/work/TeamsFx/TeamsFx/packages/server"  },  {    "name": "@microsoft/m365-spec-parser",    "version": "0.1.1-beta.2024032106.0",    "private": false,    "location": "/home/runner/work/TeamsFx/TeamsFx/packages/spec-parser"  },  {    "name": "templates",    "version": "4.2.1-beta.2024032106.0",    "private": true,    "location": "/home/runner/work/TeamsFx/TeamsFx/templates"  }]' > versions.json
          echo "VS1710P3" > series.txt
          echo "server.exe" > server.exe

      - name: upload release info to artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            changed.txt
            series.txt
            versions.json
            *.vsix
            *.exe
